# This workflow will install Python dependencies and run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test-py38:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  python3 setup.py install
            - name: Starting MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-replica-set: "yuno-test"
                  mongodb-port: 40000
            - name: Test with pytest
              run: |
                  echo "40000" > "MONGO_PORT"
                  pytest -vv

    test-py39:
        runs-on: ubuntu-latest
        services:
            mongodb:
                image: mongo
                ports:
                    - 27017:27017
        needs: test-py38
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  python3 setup.py install
            - name: Starting MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-replica-set: "yuno-test"
                  mongodb-port: 40001
            - name: Test with pytest
              run: |
                  echo "40001" > "MONGO_PORT"
                  pytest -vv

    test-py310:
        runs-on: ubuntu-latest
        services:
            mongodb:
                image: mongo
                ports:
                    - 27017:27017
        needs: test-py39
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  python3 setup.py install
            - name: Starting MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-replica-set: "yuno-test"
                  mongodb-port: 40002
            - name: Test with pytest
              run: |
                  echo "40002" > "MONGO_PORT"
                  pytest -vv
